version: '2.1'
services:
  app:
    environment:
      process.env.NODE_ENV: "dev"
    build: .
    ports:
      - "80:8080"
  database:
    container_name: "mongodb"
    image: "arm64v8/mongo:4.0-xenial"
    restart: "always"

