version: 2.1
jobs:
  build:
    working_directory: ~/leopold
    docker:
      - image: circleci/node:12.13.1
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: generate-docs
          command: npm run docs
  deploy:
    environment:
      IMAGE_NAME: building-on-ci
    docker:
      - image: circleci/node:12.13.1
    steps:
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $DOCKER_IMAGE_NAME:latest
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
