version: 2.1
jobs:
  build:
    working_directory: ~/leopold
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: docker-login
          command: "docker login -u $DOCKER_USER -p $DOCKERHUB_PASSWORD"
      - run:
          name: build-docker-image
          command: 'docker build -t pmuldoon/leopold:latest .'
      - run:
          name: push-docker-image
          command: docker push pmuldoon/leopold:latest
