version: 2.1
jobs:
  build:
    working_directory: ~/leopold
    docker:
      - image: circleci/node:12.13.1
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: generate-docs
          command: npm run docs
  deploy:
    name: Build and Push Docker image to Docker Hub
    command: |
      echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
      echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
      echo 'export IMAGE_NAME=leopold' >> $BASH_ENV && source $BASH_ENV
      docker build -t $DOCKER_USER/$IMAGE_NAME -t $DOCKER_USER/$IMAGE_NAME:$TAG .
      echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      docker push $DOCKER_USER/$IMAGE_NAME
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
