version: 2.1
jobs:
  build:
    working_directory: ~/leopold
    docker:
      - image: circleci/node:12.13.1
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
        name: generate-docs
        command: npm run docs
      - run:
          name: balena-login
          command: npm run ci-login -- --token $BALENA_CLI_TOKEN
      - run:
          name: balena-push
          command: npm run ci-deploy
